events {}
http {
  server_tokens off;

  server {
    listen 80;
    server_name 10.13.1.194;

    location /f/ {
      proxy_pass       http://bot:8080;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
      return 404;
    }
  }
}
